# System Aliases:
alias "python"="python3"
alias "py"="python"
alias "ipy"="ipython" # Interactive Python
alias "pip"="pip3"
alias "ll"="ls -l"
alias "lla"="ls -la"
alias "fzf"="fzf --preview \"less {}\""
alias "vim"="nvim"
alias "home"="cd ~"
alias "fishrc"="nvim $HOME/.config/fish/config.fish"
alias "c"="open $1 -a \"Visual Studio Code\""

alias "lg"="lazygit"
alias "gs"="git status"
alias "gd"="git diff"
alias "gf"="git fetch"
alias "gp"="git pull"
alias "gm"="git merge"
alias "gl"="git log"
alias "gb"="git branch"
alias "gc"="git add . && git commit -m"
alias "gsw"="git switch"
alias "gcb"="git checkout -b"
alias "gpu"="git push"
alias "gclean"="git clean -fd"